theme: jekyll-theme-cayman # Jekyll default theme
title: Maxime HEBRARD # Website title
description: Bio-Informatician # Website description
show_downloads: false # Theme header button
github: [metadata] # auto fetch github info
